
import './globals.css'
import { Inter } from 'next/font/google'
import ThemeRegistry from '@/components/themes/ThemeRegistry'
// import SideMenu from '@/components/sidemenu/SideMenu'
import SideMenuMUI from '@/components/sidemenu/SideMenuMUI'
import SideMenuPro from '@/components/sidemenu/SideMenuPro'
// import AppTest from '@/components/AppTest'

const inter = Inter({ subsets: ['latin'] })
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({ children }: any) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ margin: 0, padding: 0 }}>
        <ThemeRegistry options={{ key: 'hoangduc' }}>
          <SideMenuMUI>
            {children}
          </SideMenuMUI>
          {/* <SideMenuPro>
            {children}
          </SideMenuPro> */}
        </ThemeRegistry>
      </body>
    </html>
  )
}